# Generated by Django 2.2.13 on 2020-09-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20200905_2256"),
        ("accounts", "0002_auto_20200914_1452"),
    ]

    operations = []
