# Generated by Django 2.2.13 on 2020-09-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merge_20200914_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="", max_length=32, verbose_name="first_name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=32, verbose_name="last_name"),
        ),
    ]
