# Generated by Django 2.2.13 on 2020-10-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200928_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyboard_size',
            field=models.IntegerField(choices=[(25, '25'), (32, '32'), (37, '37'), (49, '49'), (61, '61'), (88, '88')], default=49),
        ),
    ]
