# Generated by Django 2.2.13 on 2021-01-12 22:06

import apps.accounts.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


def set_keyboard_size(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        user.preferences['keyboard_size'] = user.keyboard_size
        user.save()


def update_subscribers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        for supervisor in user._supervisors:
            user._supervisors_dict[supervisor.id] = 'Accepted'
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_user_keyboard_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_supervisors_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Supervisors'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 default=apps.accounts.models.get_preferences_default,
                                                                 verbose_name='Preferences'),
        ),
        migrations.RunPython(set_keyboard_size),
        migrations.RunPython(update_subscribers)
    ]
