# Generated by Django 2.2.28 on 2022-06-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_advance_delay',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_repeat_delay',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
