# Generated by Django 2.2.28 on 2022-07-10 18:21

from django.db import migrations


def forwards(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    for user in User.object.using(db_alias).all():
        user.set_password(user.raw_password)
        user.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_additional_user_preferences"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
        migrations.RemoveField(
            model_name="user",
            name="raw_password",
        ),
    ]
