# Generated by Django 2.2.28 on 2022-08-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
