# Generated by Django 2.2.28 on 2022-09-01 08:49

import re
from django.db import migrations, models


def forwards(apps, schema_editor):
    Group = apps.get_model("accounts", "Group")
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    for group in Group.objects.using(db_alias).all():
        member_list = User.objects.using(db_alias).filter(id__in=group._members)
        for user_id in member_list:
            group.add(User.objects.using(db_alias).filter(id=user_id).first())
        group.save()


def reverse(apps, schema_editor):
    Group = apps.get_model("accounts", "Group")
    db_alias = schema_editor.connection.alias
    for group in Group.objects.using(db_alias).all():
        for user in group.members.all():
            group._members = group._members + " " + user.id
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auto_20220828_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="These are the members within the group. You can add members after creating the group.",
                related_name="users",
                to="accounts.User",
            ),
        ),
        migrations.RunPython(forwards, reverse),
        migrations.RemoveField(
            model_name="group",
            name="_members",
        ),
    ]
