# Generated by Django 2.2.28 on 2022-09-05 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_group__members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_supervisors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_advance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_advance_delay',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_repeat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_repeat_delay',
        ),
        migrations.RemoveField(
            model_name='user',
            name='keyboard_size',
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
