# Generated by Django 2.2.28 on 2022-10-18 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220906_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='The users within your group. You can add users after creating the group.', related_name='participant_groups', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
