# Generated by Django 2.2.28 on 2023-03-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20221018_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Group name'),
        ),
    ]
