# Generated by Django 2.2.28 on 2023-12-13 21:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230321_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content_permits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Content Permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='performance_permits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Content Permissions'),
        ),
    ]
