# Generated by Django 2.2.28 on 2023-12-13 21:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20231213_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='performance_permits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Performance Permissions'),
        ),
    ]
