# Generated by Django 2.2.28 on 2023-12-14 03:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20231213_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connections_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Connections List'),
        ),
    ]
