# Generated by Django 2.2.28 on 2023-12-19 23:23

from django.db import migrations


def forwards(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        for supervisor_id, accepted_status in user._supervisors_dict.items():
            if accepted_status == "Accepted":
                user = User.objects.using(db_alias).get(pk=user.pk)
                supervisor = User.objects.using(db_alias).get(pk=supervisor_id)
                # Might be a better way to do this: fetches fresh version of user since it could've been a supervisor that's been .save()'d in the meantime
                user.performance_permits.append(supervisor.pk)
                supervisor.content_permits.append(user.pk)
                user.save()
                supervisor.save()


def backwards(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        supervisors_dict = {}
        for supervisor_id in user.performance_permits:
            supervisor = User.objects.using(db_alias).get(pk=supervisor_id)
            if user.pk in supervisor.content_permits:
                supervisors_dict[supervisor.pk] = "Accepted"
        user._supervisors_dict = supervisors_dict
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_user_connections_list"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
