# Generated by Django 2.2.28 on 2023-12-21 20:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_subscriber_permits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_supervisors_dict',
        ),
        migrations.AlterField(
            model_name='user',
            name='content_permits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Content Permits'),
        ),
        migrations.AlterField(
            model_name='user',
            name='performance_permits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Performance Permissions'),
        ),
    ]
