# Generated by Django 2.2.13 on 2020-06-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTICourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name_short', models.CharField(max_length=1024)),
                ('course_name', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name': 'LTI Course',
                'verbose_name_plural': 'LTI Courses ',
                'ordering': ['course_name_short', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='LTIConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=255)),
                ('resource_link_id', models.CharField(max_length=255)),
                ('context_id', models.CharField(blank=True, max_length=255, null=True)),
                ('canvas_course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_tool.LTICourse')),
            ],
            options={
                'verbose_name': 'LTI Consumer',
                'ordering': ['consumer_key', 'resource_link_id', 'context_id'],
            },
        ),
    ]
