# Generated by Django 2.2.13 on 2020-08-22 13:51

import apps.exercises.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="_ID",
                    ),
                ),
                ("id", models.CharField(max_length=16, unique=True, verbose_name="ID")),
                (
                    "name",
                    models.CharField(max_length=32, unique=True, verbose_name="Name"),
                ),
                (
                    "exercises",
                    models.CharField(
                        help_text="Ordered set of exercise IDs, separated by comma.",
                        max_length=1024,
                        verbose_name="Exercises",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "authored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="_ID",
                    ),
                ),
                ("id", models.CharField(max_length=16, unique=True, verbose_name="ID")),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(verbose_name="Data"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Is Public"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "authored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
            },
        ),
        migrations.CreateModel(
            name="PerformanceData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=apps.exercises.models.get_default_data,
                        verbose_name="Raw Data",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_data",
                        to="exercises.Playlist",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervisor_performance_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance",
                "verbose_name_plural": "Performances",
                "unique_together": {("user", "playlist")},
            },
        ),
    ]
