# Generated by Django 2.2.13 on 2020-08-26 16:17

import apps.exercises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20200824_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rhythm_value',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Rhythm Value'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='data',
            field=apps.exercises.models.RawJSONField(verbose_name='Data'),
        ),
    ]
