# Generated by Django 2.2.13 on 2020-12-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20201220_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for reminder', max_length=60, null=True, verbose_name='Name'),
        ),
    ]
