# Generated by Django 2.2.13 on 2020-12-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0008_auto_20201220_2001"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="rhythm_value",
            new_name="rhythm",
        ),
    ]
