# Generated by Django 2.2.13 on 2021-01-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0010_auto_20201229_1122"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Is Public"),
        ),
        migrations.AddField(
            model_name="playlist",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Is Public"),
        ),
    ]
