# Generated by Django 2.2.13 on 2021-01-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0015_auto_20210125_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="rhythm",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Rhythm"
            ),
        ),
    ]
