# Generated by Django 2.2.13 on 2021-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0015_auto_20210125_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="is_auto",
            field=models.BooleanField(
                default=False, verbose_name="Is Automatic Playlist"
            ),
        ),
    ]
