# Generated by Django 2.2.13 on 2021-02-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_playlist_is_auto'),
        ('exercises', '0016_auto_20210126_0154'),
    ]

    operations = [
    ]
