# Generated by Django 2.2.24 on 2021-08-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0018_auto_20210203_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="time_signature",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Meter"
            ),
        ),
    ]
