# Generated by Django 2.2.24 on 2021-08-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_exercise_time_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time_signature',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Meter'),
        ),
    ]
