# Generated by Django 2.2.28 on 2022-07-28 20:26
import re
import operator
import apps.exercises.models
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Playlist = apps.get_model("exercises", "Playlist")
    Exercise = apps.get_model("exercises", "Exercise")
    ExercisePlaylistOrdered = apps.get_model("exercises", "ExercisePlaylistOrdered")
    db_alias = schema_editor.connection.alias
    for playlist in Playlist.objects.all():
        exercise_list = re.split(r"[,; \n]+", playlist.exercises_string)
        exercise_list = list(
            map(
                lambda id: Exercise.objects.get(id=id) if id != "" else None,
                exercise_list,
            )
        )
        for i in range(0, len(exercise_list)):
            if exercise_list[i] != None:
                ExercisePlaylistOrdered.objects.using(db_alias).create(
                    exercise_id=exercise_list[i]._id,
                    playlist_id=playlist._id,
                    order=i + 1,
                )


def reverse(apps, schema_editor):
    Playlist = apps.get_model("exercises", "Playlist")
    Exercise = apps.get_model("exercises", "Exercise")
    ExercisePlaylistOrdered = apps.get_model("exercises", "ExercisePlaylistOrdered")
    db_alias = schema_editor.connection.alias
    for playlist in Playlist.objects.all():
        playlist.exercises_string = ""
        exercise_list = map(
            lambda epo: Exercise.objects.using(db_alias).get(_id=epo.exercise_id),
            sorted(
                ExercisePlaylistOrdered.objects.using(db_alias).filter(
                    playlist_id=playlist._id
                ),
                key=operator.attrgetter("order"),
            ),
        )
        for exercise in exercise_list:
            playlist.exercises_string = playlist.exercises_string + " " + exercise.id
        playlist.save()


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0022_course_visible_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="exercises",
            new_name="exercises_string",
        ),
        migrations.CreateModel(
            name="ExercisePlaylistOrdered",
            fields=[
                (
                    "_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="_ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.Exercise",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.Playlist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.exercises.models.ClonableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="playlist",
            name="exercises",
            field=models.ManyToManyField(
                help_text="These are the exercises within this playlist.",
                related_name="playlists",
                through="exercises.ExercisePlaylistOrdered",
                to="exercises.Exercise",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="exercises_string",
            field=models.CharField(
                max_length=1024, verbose_name="Exercise IDs", default=""
            ),
        ),
        migrations.RunPython(forwards, reverse_code=reverse),
        migrations.RemoveField(
            model_name="playlist",
            name="exercises",
        ),
    ]
