# Generated by Django 2.2.28 on 2022-07-28 20:26
import re
import apps.exercises.models
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Playlist = apps.get_model("exercises", "Playlist")
    Exercise = apps.get_model("exercises", "Playlist")
    for playlist in Playlist.objects.all():
        exercise_list = Exercise.objects.filter(id__in=re.split(r"[,; \n]+", playlist.exercises_string))
        for i in range(0, len(exercise_list)):
            playlist.exercises.add(exercise_list[i])
        playlist.save()


def reverse(apps, schema_editor):
    Playlist = apps.get_model("exercises", "Playlist")
    for playlist in Playlist.objects.all():
        for exercise in exercise.playlists.all():
            playlist.exercise_string = playlist.exercise_string + " " + exercise.id
        playlist.save()


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0023_auto_20220728_1355"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="exercises",
            new_name="exercises_string",
        ),
        migrations.CreateModel(
            name="ExercisePlaylistOrdered",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name="_ID")),
                ("order", models.IntegerField(verbose_name="Order")),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exercises.Exercise")),
                ("playlist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exercises.Playlist")),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.exercises.models.ClonableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="playlist",
            name="exercises",
            field=models.ManyToManyField(
                help_text="These are the exercises within this playlist.",
                related_name="playlists",
                through="exercises.ExercisePlaylistOrdered",
                to="exercises.Exercise",
            ),
        ),
        migrations.RunPython(forwards, reverse),
        migrations.RemoveField(
            model_name="playlist",
            name="exercises",
        ),
    ]
