# Generated by Django 2.2.28 on 2022-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0024_auto_20220728_1626"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="exercises_string",
        ),
        migrations.AddField(
            model_name="playlist",
            name="exercises",
            field=models.ManyToManyField(
                blank=True,
                help_text="These are the exercises within this playlist.",
                related_name="playlists",
                through="exercises.ExercisePlaylistOrdered",
                to="exercises.Exercise",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=64, unique=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="Name"),
        ),
    ]
