# Generated by Django 2.2.28 on 2022-08-28 18:34

import apps.exercises.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_auto_20220807_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistCourseOrdered',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='_ID')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('due_date', models.DateTimeField(blank=True, default=None, help_text='Format: MM-DD-YYYY', null=True, verbose_name='Due Date')),
                ('publish_date', models.DateTimeField(blank=True, default=None, help_text='Format: MM-DD-YYYY', null=True, verbose_name='Publish Date')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.exercises.models.ClonableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='course',
            name='playlists',
            field=models.ManyToManyField(blank=True, help_text='These are the exercise playlists within the course. You can add playlists after creating the course.', related_name='courses', through='exercises.PlaylistCourseOrdered', to='exercises.Playlist'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rhythm',
            field=models.CharField(blank=True, help_text="Rhythm for this exercise's notes", max_length=255, null=True, verbose_name='Rhythm'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_signature',
            field=models.CharField(blank=True, default='', help_text='Time signature for this exercise. Ex: 3/4', max_length=8, null=True, verbose_name='Meter'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='exercises',
            field=models.ManyToManyField(blank=True, help_text='These are the exercises within this playlist. You can add exercises after creating the playlist.', related_name='playlists', through='exercises.ExercisePlaylistOrdered', to='exercises.Exercise'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='transposition_type',
            field=models.CharField(blank=True, choices=[('Exercise Loop', 'Exercise Loop'), ('Playlist Loop', 'Playlist Loop'), (None, None)], help_text="Determines order of transposed exercises. Exercise Loop means that each exercise will have its transposed versions come after it successively. Playlist Loop means that the entire playlist will come in its original key, followed successively by the playlist's transposed versions.", max_length=32, null=True, verbose_name='Transposition Types'),
        ),
        migrations.AddField(
            model_name='playlistcourseordered',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Course'),
        ),
        migrations.AddField(
            model_name='playlistcourseordered',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Playlist'),
        ),
    ]
