# Generated by Django 2.2.28 on 2022-09-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0026_auto_20220828_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Sharing your course will make it available to other users. Doing so will make your email visible to people looking to use your course.', verbose_name='Share'),
        ),
        migrations.AlterField(
            model_name='course',
            name='playlists',
            field=models.ManyToManyField(blank=True, help_text='These are the exercise playlists within the course. You can add playlists after creating the course. Changing the order will automatically save all changes made in the form.', related_name='courses', through='exercises.PlaylistCourseOrdered', to='exercises.Playlist'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='If no group is selected, course will be visible to all subscribers.', related_name='visible_courses', to='accounts.Group', verbose_name='Visible Groups'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description showed to admins in the exercise dashboard table.', max_length=60, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Sharing your exercise will allow other users to include it in their playlists. Doing so will make your email visible to people looking to use this exercise.', verbose_name='Share'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rhythm',
            field=models.CharField(blank=True, help_text="Rhythm for this exercise's notes. w for a whole note, H for a dotted half note, h for a half note, and q for a quarter note. For example, if your exercise has five notes and you want it to span exactly two bars, you could input: 'H q h q q'.", max_length=255, null=True, verbose_name='Rhythm'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_signature',
            field=models.CharField(blank=True, default='', help_text='Time signature for this exercise. E.g. 3/4', max_length=8, null=True, verbose_name='Meter'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='exercises',
            field=models.ManyToManyField(blank=True, help_text='These are the exercises within this playlist. You can add exercises after creating the playlist. Changing the order will automatically save all changes made in the form.', related_name='playlists', through='exercises.ExercisePlaylistOrdered', to='exercises.Exercise'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Sharing your playlist will allow other users to include it in their courses. Doing so will make your email visible to people looking to use this playlist.', verbose_name='Share'),
        ),
        migrations.AlterField(
            model_name='playlistcourseordered',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='playlistcourseordered',
            name='order',
            field=models.IntegerField(help_text='Unit #', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='playlistcourseordered',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Publish Date'),
        ),
    ]
