# Generated by Django 2.2.28 on 2022-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0027_auto_20220906_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Sharing your exercise will allow other users to include it in their playlists. Doing so will make your email visible to people looking to use this exercise.', verbose_name='Share'),
        ),
    ]
