# Generated by Django 2.2.28 on 2022-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0028_auto_20220918_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
    ]
