# Generated by Django 2.2.28 on 2022-09-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0028_auto_20220905_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='ID'),
        ),
    ]
