# Generated by Django 2.2.28 on 2022-11-01 01:14

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0029_course_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancedata",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performance_data",
                to="exercises.Course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="open",
            field=models.BooleanField(
                default=True,
                help_text="Open courses can be viewed by your subscribers who have not performed any playlists within it.",
                verbose_name="Open",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancedata",
            unique_together={("user", "playlist", "course")},
        ),
    ]
