# Generated by Django 2.2.28 on 2022-11-04 01:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0030_auto_20221031_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='performance_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Performances'),
        ),
    ]
