# Generated by Django 2.2.28 on 2022-11-09 19:15
import pytz
from django.db import migrations
from django.conf import settings


def push_back_due_dates(apps, schema_editor):
    PlaylistCourseOrdered = apps.get_model("exercises", "PlaylistCourseOrdered")
    db_alias = schema_editor.connection.alias
    for pco in PlaylistCourseOrdered.objects.using(db_alias).all():
        if pco.due_date:
            pco.due_date = pco.due_date.replace(tzinfo=pytz.utc).astimezone(
                pytz.timezone(settings.TIME_ZONE)
            )
            pco.due_date = pco.due_date.replace(hour=23, minute=59, second=59)
            # pco.due_date = pytz.timezone(settings.TIME_ZONE).localize(pco.due_date)
        pco.save()


def reverse(apps, schema_editor):
    PlaylistCourseOrdered = apps.get_model("exercises", "PlaylistCourseOrdered")
    db_alias = schema_editor.connection.alias
    for pco in PlaylistCourseOrdered.objects.using(db_alias).all():
        if pco.due_date:
            pco.due_date = pco.due_date.replace(tzinfo=None)
        pco.save()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0031_course_performance_dict"),
    ]

    operations = [migrations.RunPython(push_back_due_dates, reverse_code=reverse)]
