# Generated by Django 2.2.28 on 2022-11-09 21:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0032_auto_20221109_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="performance_dict",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name="Performances"
            ),
        ),
    ]
