# Generated by Django 2.2.28 on 2023-01-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0033_auto_20221109_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='rhythm',
            field=models.CharField(blank=True, help_text="Length of each chord in this exercise. w for a whole note, H for a dotted half note, h for a half note, and q for a quarter note. For example, if your exercise has five chords and you want it to span exactly two bars, you could input: 'H q h q q'.", max_length=255, null=True, verbose_name='Rhythm'),
        ),
    ]
