# Generated by Django 2.2.28 on 2023-01-20 03:36

from django.db import migrations


def bump_zero_orders(apps, schema_editor):
    PlaylistCourseOrdered = apps.get_model("exercises", "PlaylistCourseOrdered")
    ExercisePlaylistOrdered = apps.get_model("exercises", "ExercisePlaylistOrdered")
    db_alias = schema_editor.connection.alias
    zero_pcos = PlaylistCourseOrdered.objects.using(db_alias).filter(order=0)
    for pco in zero_pcos:
        parent_course_id = pco.course_id
        sibling_pcos = PlaylistCourseOrdered.objects.using(db_alias).filter(
            course_id=parent_course_id
        )
        for sibling_pco in sibling_pcos:
            sibling_pco.order += 1
            sibling_pco.save()
    zero_epos = ExercisePlaylistOrdered.objects.using(db_alias).filter(order=0)
    for epo in zero_epos:
        parent_playlist_id = epo.playlist_id
        sibling_epos = ExercisePlaylistOrdered.objects.using(db_alias).filter(
            playlist_id=parent_playlist_id
        )
        for sibling_epo in sibling_epos:
            sibling_epo.order += 1
            sibling_epo.save()


def reverse():
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0036_auto_20230118_1959"),
    ]

    operations = [migrations.RunPython(bump_zero_orders, reverse_code=reverse)]
