# Generated by Django 2.2.28 on 2023-01-24 23:50
from datetime import datetime, time
from pytz import timezone
from django.db import migrations
from django.conf import settings


def forwards(apps, schema_editor):
    PlaylistCourseOrdered = apps.get_model("exercises", "PlaylistCourseOrdered")
    db_alias = schema_editor.connection.alias
    for pco in PlaylistCourseOrdered.objects.using(db_alias).all():
        if pco.due_date != None:
            pco.due_date = datetime.combine(pco.due_date, time.max).astimezone(
                timezone(settings.TIME_ZONE)
            )
        if pco.publish_date != None:
            pco.publish_date = datetime.combine(pco.publish_date, time.min).astimezone(
                timezone(settings.TIME_ZONE)
            )
        pco.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0039_auto_20230123_2005"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=reverse),
    ]
