# Generated by Django 2.2.28 on 2023-01-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0040_timezone_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='transposition_type',
            field=models.CharField(blank=True, choices=[(None, 'No transposition'), ('Exercise Loop', 'Loop keys for each exercise'), ('Playlist Loop', 'Loop exercises for each key')], help_text='Apply transposition operations to the list of exercises.', max_length=32, null=True, verbose_name='Transposition Types'),
        ),
    ]
