# Generated by Django 2.2.28 on 2023-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0044_rename_json_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='C-ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Sharing your course may, in future, make it available to other users for copying and editing as they wish. If so, your email address will be revealed to all users of the site.', verbose_name='Commons'),
        ),
        migrations.AlterField(
            model_name='course',
            name='open',
            field=models.BooleanField(default=True, help_text='This course will be displayed to ALL your performer connections, whether or not you included them in the groups below.', verbose_name='Visible to ALL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='courses', through='exercises.PlaylistCourseOrdered', to='exercises.Playlist'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='This course will ALWAYS be displayed to performer connections who are members of these groups.', related_name='visible_courses', to='accounts.Group', verbose_name='Performer Groups'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='E-ID'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='exercises.ExercisePlaylistOrdered', to='exercises.Exercise'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='P-ID'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='This box is checked if AnalyticPiano generated the playlist from your newly created exercises and you made no edits.', verbose_name='Auto-generated'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Sharing your playlist will allow other users to include it in their courses. Doing so will reveal your email address to all users of the site.', verbose_name='Commons'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='transposition_type',
            field=models.CharField(blank=True, choices=[(None, 'No transposition'), ('Exercise Loop', 'Loop all keys for each exercise'), ('Playlist Loop', 'Loop all exercises for each key')], help_text='Apply transposition operations to the list of exercises.', max_length=32, null=True, verbose_name='Transposition Types'),
        ),
    ]
