# Generated by Django 2.2.28 on 2023-03-21 18:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0045_auto_20230321_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tardy_threshold',
            field=models.IntegerField(default=120, verbose_name='Tardiness threshold (hours)'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(tardy_penalty__lte=django.db.models.expressions.F('points_per_playlist')), name='course_tardy_penalty_lte_points_per_playlist'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(tardy_penalty__lte=django.db.models.expressions.F('late_penalty')), name='course_tardy_penalty_lte_late_penalty'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(late_penalty__lte=django.db.models.expressions.F('points_per_playlist')), name='course_late_penalty_lte_points_per_playlist'),
        ),
    ]
