# Generated by Django 2.2.28 on 2023-03-26 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0047_auto_20230322_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='late_penalty',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Late Penalty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tardy_penalty',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tardy penalty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tardy_threshold',
            field=models.IntegerField(default=120, help_text="When performances are submitted after the due date, this threshold determines if they're considered tardy or late. Submissions before this threshold are tardy, submissions after are late.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Late threshold'),
        ),
    ]
