# Generated by Django 2.2.28 on 2023-12-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0049_auto_20231120_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='This course will ALWAYS be displayed to performer connections who are members of these groups.', related_name='visible_courses', to='accounts.Group', verbose_name='User Groups'),
        ),
    ]
