# Generated by Django 2.2.28 on 2023-12-14 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0050_auto_20231214_0047'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='course_tardy_penalty_lte_points_per_playlist',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='course_tardy_penalty_lte_late_penalty',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='course_late_penalty_lte_points_per_playlist',
        ),
        migrations.RemoveField(
            model_name='course',
            name='late_penalty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='points_per_playlist',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tardy_penalty',
        ),
        migrations.AddField(
            model_name='course',
            name='late_credit',
            field=models.DecimalField(decimal_places=1, default=0.6, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Points per playlist when late'),
        ),
        migrations.AddField(
            model_name='course',
            name='tardy_credit',
            field=models.DecimalField(decimal_places=1, default=0.9, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Points per playlist when tardy'),
        ),
        migrations.AddField(
            model_name='course',
            name='timely_credit',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Points per playlist when timely'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tardy_threshold',
            field=models.IntegerField(default=120, help_text='When performances are submitted after the due date, this threshold determines if they are considered tardy or late. Submissions before this threshold are tardy, submissions after are late.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4320)], verbose_name='Late threshold (hours)'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(tardy_credit__lte=django.db.models.expressions.F('timely_credit')), name='course_tardy_credit_lte_timely_credit'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(late_credit__lte=django.db.models.expressions.F('timely_credit')), name='course_late_credit_lte_timely_credit'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(late_credit__lte=django.db.models.expressions.F('tardy_credit')), name='course_late_credit_lte_tardy_credit'),
        ),
    ]
