# Generated by Django 2.2.28 on 2023-12-14 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0051_auto_20231214_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='late_credit',
            field=models.DecimalField(decimal_places=1, default=0.6, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Points per playlist if late'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tardy_credit',
            field=models.DecimalField(decimal_places=1, default=0.9, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Points per playlist if tardy'),
        ),
        migrations.AlterField(
            model_name='course',
            name='timely_credit',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Points per playlist if timely'),
        ),
    ]
