# Generated by Django 2.2.28 on 2023-12-17 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0052_auto_20231214_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='authored_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Author of Course'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='authored_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Author of Playlist'),
        ),
    ]
